# Generated by Django 4.0.4 on 2022-05-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_order_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='transaction_id',
            new_name='date_added',
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
