# Generated by Django 4.0.4 on 2022-05-19 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
