# Generated by Django 4.0.4 on 2022-05-27 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_wishlist_products_wishlist_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
